### ISSUE TITLE
app doesn't load properly

### ISSUE THREAD

**Issue by codeforkjeff** [cmoa/elysa#84]
I followed the instructions in the README and got foreman running the app. However, trying to load http://localhost:5000/ results in a blank page. When I open the console, and inspect the requests being made, I see that the content returned for http://localhost:5000/js/ember-app.js isn't the javascript file, but the index page HTML, since that URL is being matched to the "get '/*'" route. I can see Firefox  choking on it when trying to interpret it as javascript and giving the error  "SyntaxError: expected expression, got '<'1 ember-app.js:1:0"

Am I missing a step to get Sinatra to serve /js/ember-app.js properly, or is there an issue in the code?

**Comment by codeforkjeff** [comment]
Er, scratch that. I now see that guard is being used to compile the JS and put it into /public/js/. But foreman doesn't start up guard properly. I get this error:

22:57:15 guard.1         | 22:57:15 - ERROR - Invalid Guardfile, original error is: 
22:57:15 guard.1         | > [#] 
22:57:15 guard.1         | > [#] superclass must be a Class (Module given), 
22:57:15 guard.1         | > [#] backtrace: 
22:57:15 guard.1         | > [#] 	(dsl)> ./Guardfile:21:in `<module:Guard>'
22:57:15 guard.1         | > [#] 	(dsl)> ./Guardfile:20:in `evaluate'
22:57:15 guard.1         | > [#] 	(dsl)> $GEM_HOME/gems/guard-2.12.9/lib/guard/dsl.rb:377:in `instance_eval'
22:57:15 guard.1         | > [#] 	(dsl)> $GEM_HOME/gems/guard-2.12.9/lib/guard/dsl.rb:377:in `evaluate'
22:57:15 guard.1         | > [#] 	(dsl)> $GEM_HOME/gems/guard-2.12.9/lib/guard/guardfile/evaluator.rb:91:in `evaluate'
22:57:15 guard.1         | > [#] 	(dsl)> $GEM_HOME/gems/guard-2.12.9/lib/guard.rb:134:in `_evaluate'
22:57:15 guard.1         | > [#] 	(dsl)> $GEM_HOME/gems/guard-2.12.9/lib/guard.rb:49:in `setup'
22:57:15 guard.1         | > [#] 	(dsl)> $GEM_HOME/gems/guard-2.12.9/lib/guard/commander.rb:32:in `start'
22:57:15 guard.1         | > [#] 	(dsl)> $GEM_HOME/gems/guard-2.12.9/lib/guard/cli/environments/valid.rb:16:in `start_guard'
22:57:15 guard.1         | > [#] 	(dsl)> $GEM_HOME/gems/guard-2.12.9/lib/guard/cli.rb:122:in `start'
22:57:15 guard.1         | > [#] 	(dsl)> /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
22:57:15 guard.1         | > [#] 	(dsl)> /usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
22:57:15 guard.1         | > [#] 	(dsl)> /usr/lib/ruby/vendor_ruby/thor.rb:359:in `dispatch'
22:57:15 guard.1         | > [#] 	(dsl)> /usr/lib/ruby/vendor_ruby/thor/base.rb:440:in `start'
22:57:15 guard.1         | > [#] 	(dsl)> $GEM_HOME/gems/guard-2.12.9/lib/guard/aruba_adapter.rb:32:in `execute'
22:57:15 guard.1         | > [#] 	(dsl)> $GEM_HOME/gems/guard-2.12.9/lib/guard/aruba_adapter.rb:19:in `execute!'
22:57:15 guard.1         | > [#] 	(dsl)> $GEM_HOME/gems/guard-2.12.9/bin/_guard-core:11:in `<main>'
22:57:15 guard.1         | exited with code 1

I'm not very familiar with guard, but it looks to me like the EmberHandlebars plugin defined in the Guardfile is inheriting from an obsolete class (in an older version of guard?). If I change the relevant lines to this:

module ::Guard
  class EmberHandlebars < Plugin
    def initialize(options = {})
      super(options)

Guard seems to work, but it gives me a warning:

22:58:22 guard.1         | 22:58:22 - WARN - Starting with Guard 2.0 'Guard.guards(filter)' is deprecated.
22:58:22 guard.1         | > [#] Please use 'Guard.plugins(filter)' instead.
22:58:22 guard.1         | > [#] For more information on how to upgrade for Guard 2.0, please head
22:58:22 guard.1         | > [#] over to: https://github.com/guard/guard/wiki/Upgrading-to-Guard-2.0#deprecated-methods
22:58:22 guard.1         | > [#] 
22:58:22 guard.1         | > [#] Deprecation backtrace: /home/jeffchiu/.gem/ruby/2.1.0/gems/guard-2.12.9/lib/guard/ui.rb:108:in `deprecation'
22:58:22 guard.1         | > [#] 	 >/home/jeffchiu/.gem/ruby/2.1.0/gems/guard-2.12.9/lib/guard/deprecated/guard.rb:37:in `guards'
22:58:22 guard.1         | > [#] 	 >/home/jeffchiu/elysa/Guardfile:44:in `notify'
22:58:22 guard.1         | > [#] 	 >/home/jeffchiu/elysa/Guardfile:40:in `run_on_change'
22:58:22 guard.1         | > [#] 	 >/home/jeffchiu/elysa/Guardfile:29:in `run_all'

**Comment by codeforkjeff** [comment]
I tried to update the Guardfile to work with guard 2.13.0. There have been many changes, detailed here:

https://github.com/guard/guard/wiki/Upgrading-to-Guard-2.0

guard will run, but as noted in the code, it doesn't compile the JS files correctly: when the watch is triggered, it seems to compile the ALREADY compiled files, and havoc ensues. My changes were minimal, so I don't know why this is happening; it's possible the behavior of Watcher.match_files has changed.

https://github.com/codeforkjeff/elysa/commit/1ccdd79f145325a3a785295e5ab80c1192177884
